gazebo_ros_control:
  pid_gains:
     #back_caster_joint: {p: 0.0, i: 0.0, d: 0.0}
     #front_caster_joint: {p: 0.0, i: 0.0, d: 0.0}
     lt_wheel_joint: {p: 2.0, i: 0, d: 0} 
     rt_wheel_joint: {p: 2.0, i: 0, d: 0}